# Generated by Django 3.2.3 on 2021-05-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('area', models.CharField(choices=[('DESARROLLO', 'DESARROLLO'), ('DISEÑO', 'DISEÑO'), ('VENTAS', 'VENTAS')], max_length=100)),
            ],
        ),
    ]
