# Generated by Django 3.2.3 on 2021-05-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=1, unique=True)),
                ('foto', models.ImageField(blank=True, upload_to='foto/')),
            ],
        ),
    ]
